name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches: staging

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: 'npm'

      # Install dependencies and build project
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Configure AWS credentials depending on branch
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: ${{ env.AWS_REGION }}

      # Sync to correct bucket
      - name: Sync files to S3 (Production)
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync ./dist s3://angular-admin-prod --delete

      - name: Sync files to S3 (Staging)
        if: github.ref == 'refs/heads/staging'
        run: aws s3 sync ./dist s3://angular-admin-staging1 --delete

      # Invalidate correct CloudFront
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"

      # Notify if something fails
      - name: Notify on failure
        if: failure()
        run: echo "Deployment failed! Please check credentials or AWS config."
